# Welcome to Jekyll!

# Website settings
title: Rohan Deo
description: Rohan Deo GitHub Portfolio.
keywords: Rohan, Deo, rohandeo, RohanDeo18, RohanDeo1802
# baseurl:  /Jalpc # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
# url: https://example.com
url: https://RohanDeo18.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Rohan Deo  # Be used at blog posts' author.
  first_name: Rohan  # Be used at index page about me section.
  last_name: Deo  # Be used at index page about me section.
  avatar: /static/assets/img/landing/Profile_Github.jpg  # upload your avatar at directory and edit it.
  github_username: RohanDeo18  # Leave blank if you don't have now
  linkedin_id: Rohan-Deo # Leave blank if you don't have now
  facebook_username:
  twitter_username:
  email: rdeo@andrew.cmu.edu  # Leave blank if you don't have now
  cv: /static/assets/Resume_RohanDeo.pdf # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-git
    - name: icon-python
  skill_icon2:
    - name: icon-java-bold
    - name: icon-shell
  desc: Welcome to my homepage. I am a graduate student at Carnegie Mellon University in the department of Electrical and Computer Engineering. I am passionate about AI and Data Science and their applications, particularly in areas of online retail, healthcare, robotics and self-driving cars and would love to collaborate on any interesting project that you might have. I am also a bibliophile and love conversing about historical and geopolitical topics whenever the opportunity presents itself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  # name: jalpc

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id: UA-93473370-3

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: off  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
